services:
  - type: web
    name: url-anchor-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run url_status_checker.py --server.port=$PORT --server.enableCORS=false
    plan: free
